root    = "."
tmp_dir = "tmp"

# Turn on polling (in case your FS events aren’t firing)
poll = true                                        # :contentReference[oaicite:0]{index=0}

[build]
cmd         = "go build -o adam-younes main.go"
bin         = "adam-younes"
# watch .go, .html AND .css
include_ext = ["go", "html", "css"]               # :contentReference[oaicite:1]{index=1}
# explicitly watch both your templates and static folders
include_dir = ["templates", "static"]             # :contentReference[oaicite:2]{index=2}
kill_mode    = "signal"         # send signal to process
kill_signal  = "SIGTERM"        # try TERM first
kill_timeout = "2s"             # wait up to 2 seconds, then SIGKILL

[log]
time = false

[live_reload]
enable = true
port   = 35729

[proxy]
enabled    = true
proxy_port = 3000
app_port   = 8080

