name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run linters
        run: |
          go fmt ./...
          go vet ./...

      - name: Run tests
        run: go test ./... -v

      - name: Build Linux binary
        run: GOOS=linux GOARCH=amd64 go build -o adam-younes .

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: adam-younes
          path: adam-younes

  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: adam-younes

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Sync to server
        run: |
          rsync -avz --delete \
            adam-younes \
            static/ templates/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_DIR }}

      - name: Restart Go service
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            sudo systemctl restart adam-younes

      - name: Reload Caddy
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            sudo systemctl reload caddy

