name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run linters
        run: |
          go fmt ./...
          go vet ./...

      - name: Run unit tests
        run: go test ./... -v

      - name: Build Linux binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o adam-younes

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: adam-younes
          path: adam-younes

  deploy:
    name: Deploy to server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (for static/ & templates/)
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: adam-younes

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Install rsync & ssh-client
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync openssh-client

      - name: Sync static assets & templates
        run: |
          rsync -avz \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            static/ templates/ \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_DIR }}

      - name: Deploy binary into /usr/local/bin
        run: |
          # Copy the new binary into /tmp on the server
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            adam-younes \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp/adam-younes.new

          # Atomically move & set exec perms (requires passwordless sudo)
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            sudo mv /tmp/adam-younes.new /usr/local/bin/adam-younes && \
            sudo chmod +x /usr/local/bin/adam-younes

      - name: Restart Go service on server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            sudo systemctl restart adam-younes

      - name: Reload Caddy to pick up any config or static changes
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            sudo systemctl reload caddy

